language: android

android: 
  components: 
    - build-tools-26.0.0
    - android-26 
    
    # Additional components 
    - extra-android-m2repository
    
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17